load("@contrib_rules_jvm//java:defs.bzl", "java_junit5_test")
load("@rules_java//java:defs.bzl", "java_library")
load("//tools:java_test_settings.bzl", "JUNIT_DEPS", "JUNIT_RUNTIME_DEPS", "TEST_JVM_FLAGS")

java_library(
    name = "test-lib",
    testonly = True,
    srcs = glob(["*.java"]),
    deps = JUNIT_DEPS + ["//core-model/src/main/java/com/holtherndon/bazelviz/core/redact"],
)

java_junit5_test(
    name = "RedactorTest",
    jvm_flags = TEST_JVM_FLAGS,
    runtime_deps = [":test-lib"] + JUNIT_RUNTIME_DEPS,
    test_class = "com.holtherndon.bazelviz.core.redact.RedactorTest",
)

test_suite(
    name = "tests",
    tests = [":RedactorTest"],
    visibility = ["//visibility:public"],
)
