load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "test-support",
    exports = [
        "//core-model",
        "//proto",
        "//test-support/src/main/java/com/holtherndon/bazelviz/testsupport/bazel",
        "//test-support/src/main/java/com/holtherndon/bazelviz/testsupport/bep",
        "//test-support/src/main/java/com/holtherndon/bazelviz/testsupport/synthetic",
        "@maven//:com_google_protobuf_protobuf_java_util",
    ],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "tests",
    tests = [
        "//test-support/src/test/java/com/holtherndon/bazelviz/testsupport/bep:tests",
        "//test-support/src/test/java/com/holtherndon/bazelviz/testsupport/synthetic:tests",
    ],
)
