load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "graph-core",
    exports = [
        "//core-model",
        "//graph-core/src/main/java/com/holtherndon/bazelviz/graph",
    ],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "tests",
    tests = ["//graph-core/src/test/java/com/holtherndon/bazelviz/graph:tests"],
)
