load("@contrib_rules_jvm//java:defs.bzl", "java_junit5_test")
load("@rules_java//java:defs.bzl", "java_library")
load("//tools:java_test_settings.bzl", "JUNIT_DEPS", "JUNIT_RUNTIME_DEPS", "TEST_JVM_FLAGS")

java_library(
    name = "tests_lib",
    srcs = [
        "EventFilterTest.java",
        "EventIngestScaleTest.java",
        "EventQueriesTest.java",
        "EventWriterTest.java",
        "StringDictionaryTest.java",
        "TestSession.java",
    ],
    deps = JUNIT_DEPS + [
        "//core-model/src/main/java/com/holtherndon/bazelviz/core/filter",
        "//core-model/src/main/java/com/holtherndon/bazelviz/core/event:event",
        "//storage-sqlite/src/main/java/com/holtherndon/bazelviz/storage/events:events",
        "//storage-sqlite/src/main/java/com/holtherndon/bazelviz/storage/schema:schema",
        "//storage-sqlite/src/main/java/com/holtherndon/bazelviz/storage:storage",
    ],
    testonly = True,
    visibility = ["//visibility:public"],
)

java_junit5_test(
    name = "EventIngestScaleTest",
    jvm_flags = TEST_JVM_FLAGS,
    runtime_deps = [
        ":tests_lib",
    ] + JUNIT_RUNTIME_DEPS,
    test_class = "com.holtherndon.bazelviz.storage.events.EventIngestScaleTest",
    visibility = ["//visibility:public"],
)

java_junit5_test(
    name = "EventQueriesTest",
    jvm_flags = TEST_JVM_FLAGS,
    runtime_deps = [
        ":tests_lib",
    ] + JUNIT_RUNTIME_DEPS,
    test_class = "com.holtherndon.bazelviz.storage.events.EventQueriesTest",
    visibility = ["//visibility:public"],
)

java_junit5_test(
    name = "EventWriterTest",
    jvm_flags = TEST_JVM_FLAGS,
    runtime_deps = [
        ":tests_lib",
    ] + JUNIT_RUNTIME_DEPS,
    test_class = "com.holtherndon.bazelviz.storage.events.EventWriterTest",
    visibility = ["//visibility:public"],
)

java_junit5_test(
    name = "StringDictionaryTest",
    jvm_flags = TEST_JVM_FLAGS,
    runtime_deps = [
        ":tests_lib",
    ] + JUNIT_RUNTIME_DEPS,
    test_class = "com.holtherndon.bazelviz.storage.events.StringDictionaryTest",
    visibility = ["//visibility:public"],
)

test_suite(
    name = "tests",
    tests = [
        ":EventFilterTest",
        ":EventIngestScaleTest",
        ":EventQueriesTest",
        ":EventWriterTest",
        ":StringDictionaryTest",
    ],
    visibility = ["//visibility:public"],
)

java_junit5_test(
    name = "EventFilterTest",
    test_class = "com.holtherndon.bazelviz.storage.events.EventFilterTest",
    jvm_flags = TEST_JVM_FLAGS,
    runtime_deps = JUNIT_RUNTIME_DEPS + [":tests_lib"],
)
