load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "plan",
    srcs = glob(["*.java"]),
    deps = [
        "//core-model/src/main/java/com/holtherndon/bazelviz/core/source",
        "//runner/src/main/java/com/holtherndon/bazelviz/runner/caps",
        "//runner/src/main/java/com/holtherndon/bazelviz/runner/command",
    ],
    visibility = ["//visibility:public"],
)
