load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "enrich",
    srcs = glob(["*.java"]),
    deps = [
        "//core-model/src/main/java/com/holtherndon/bazelviz/core/enrich",
        "//storage-sqlite/src/main/java/com/holtherndon/bazelviz/storage/enrich",
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/inspect",
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/session",
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/theme",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
