alias(
    name = "bazel-runner",
    actual = "//runner:runner",
    visibility = ["//visibility:public"],
)

test_suite(
    name = "tests",
    tests = ["//runner:tests"],
    visibility = ["//visibility:public"],
)

alias(
    name = "RealBazelCapabilityTest",
    actual = "//runner/src/test/java/com/holtherndon/bazelviz/runner/caps:RealBazelCapabilityTest",
    visibility = ["//visibility:public"],
)
