load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "bep-codec",
    exports = [
        "//core-model",
        "//proto",
        "//bep-codec/src/main/java/com/holtherndon/bazelviz/bepcodec",
        "//bep-codec/src/main/java/com/holtherndon/bazelviz/bepcodec/entity",
    ],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "tests",
    tests = ["//bep-codec/src/test/java/com/holtherndon/bazelviz/bepcodec:tests"],
)
