load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "session-format",
    exports = [
        "//core-model",
        "//session-format/src/main/java/com/holtherndon/bazelviz/format/journal",
        "//session-format/src/main/java/com/holtherndon/bazelviz/format/portable",
        "//session-format/src/main/java/com/holtherndon/bazelviz/format/session",
        "//session-format/src/main/java/com/holtherndon/bazelviz/format/session/json",
    ],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "tests",
    tests = [
        "//session-format/src/test/java/com/holtherndon/bazelviz/format/journal:tests",
        "//session-format/src/test/java/com/holtherndon/bazelviz/format/portable:tests",
        "//session-format/src/test/java/com/holtherndon/bazelviz/format/session:tests",
        "//session-format/src/test/java/com/holtherndon/bazelviz/format/session/json:tests",
    ],
)
