load("@contrib_rules_jvm//java:defs.bzl", "java_junit5_test")
load("@rules_java//java:defs.bzl", "java_library")
load("//tools:java_test_settings.bzl", "JUNIT_DEPS", "JUNIT_RUNTIME_DEPS", "TEST_JVM_FLAGS")

java_library(
    name = "tests_lib",
    srcs = [
        "BepFixtures.java",
        "BinaryBepParserTest.java",
        "BinaryBepTailReaderTest.java",
        "RecordingSink.java",
    ],
    deps = JUNIT_DEPS + [
        "//capture-file/src/main/java/com/holtherndon/bazelviz/capture/file/binary:binary",
        "//core-model/src/main/java/com/holtherndon/bazelviz/core/source:source",
        "//proto:proto",
    ],
    testonly = True,
    visibility = ["//visibility:public"],
)

java_junit5_test(
    name = "BinaryBepParserTest",
    jvm_flags = TEST_JVM_FLAGS,
    runtime_deps = [
        ":tests_lib",
    ] + JUNIT_RUNTIME_DEPS,
    test_class = "com.holtherndon.bazelviz.capture.file.binary.BinaryBepParserTest",
    visibility = ["//visibility:public"],
)

java_junit5_test(
    name = "BinaryBepTailReaderTest",
    jvm_flags = TEST_JVM_FLAGS,
    runtime_deps = [
        ":tests_lib",
    ] + JUNIT_RUNTIME_DEPS,
    test_class = "com.holtherndon.bazelviz.capture.file.binary.BinaryBepTailReaderTest",
    visibility = ["//visibility:public"],
)

test_suite(
    name = "tests",
    tests = [
        ":BinaryBepParserTest",
        ":BinaryBepTailReaderTest",
    ],
    visibility = ["//visibility:public"],
)
