load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "analysis-core",
    exports = [
        "//core-model",
        "//graph-core",
        "//analysis-core/src/main/java/com/holtherndon/bazelviz/analysis",
    ],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "tests",
    tests = ["//analysis-core/src/test/java/com/holtherndon/bazelviz/analysis:tests"],
)
