load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "graph",
    srcs = glob(["*.java"]),
    deps = [
        "//analysis-core/src/main/java/com/holtherndon/bazelviz/analysis",
        "//core-model/src/main/java/com/holtherndon/bazelviz/core/graph",
        "//core-model/src/main/java/com/holtherndon/bazelviz/core/text",
        "//graph-core/src/main/java/com/holtherndon/bazelviz/graph",
        "//storage-sqlite/src/main/java/com/holtherndon/bazelviz/storage/graph",
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/nav",
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/session",
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/theme",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
