load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "detect",
    srcs = [
        "DetectedFormat.java",
        "FormatDetection.java",
        "FormatDetector.java",
        "StreamDetection.java",
    ],
    deps = [
        "//core-model/src/main/java/com/holtherndon/bazelviz/core/journal:journal",
        "//proto:proto",
        "@maven//:com_google_protobuf_protobuf_java",
    ],
    visibility = ["//visibility:public"],
)
