load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "bepcodec",
    srcs = glob(["*.java"]),
    deps = [
        "//bep-codec/src/main/java/com/holtherndon/bazelviz/bepcodec/entity:entity",
        "//core-model/src/main/java/com/holtherndon/bazelviz/core/event",
        "//core-model/src/main/java/com/holtherndon/bazelviz/core/journal",
        "//proto",
    ],
    visibility = ["//visibility:public"],
)
