load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "filter",
    srcs = glob(["*.java"]),
    deps = [
        "//core-model/src/main/java/com/holtherndon/bazelviz/core/filter",
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/theme",
    ],
    visibility = ["//visibility:public"],
)
