load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "starlark",
    srcs = glob(["*.java"]),
    deps = [
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/files",
        "//analysis-core/src/main/java/com/holtherndon/bazelviz/analysis",
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/graph",
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/inspect",
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/lifecycle",
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/session",
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/table",
        "//ui-swing/src/main/java/com/holtherndon/bazelviz/ui/theme",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
